name: Jmeter Test Workflow
'on': push
jobs:
    test_auto:
      name: "Jmeter Load Test Workflow"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Create Folder for reports
          run: mkdir TestReports
        - name: JMeter
          uses: QAInsights/PerfAction@v3.1
          with:
            test-plan-path: Jmeter_GitWorkflow.jmx
            args: "-e -o Jmeter_Report"
        - name: 'Upload Report'
          if: ${{ always() }}
          uses: actions/upload-artifact@v3
          with:
            name: Jmeter_Report
            path: TestReports
            retention-days: 2
